src/models.py
from . import db
from flask_login import UserMixin

class User(db.Model, UserMixin):
    id = db.Column(db.Integer, primary_key=True)
    email = db.Column(db.String(300), unique=True)
    name = db.Column(db.String(300))
    password = db.Column(db.String(150))
    files = db.relationship("Files")

    def __init__(self, email, name, password) -> None:
        self.email = email
        self.name = name
        self.password = password

class Files(db.Model, UserMixin):
    id = db.Column(db.Integer, primary_key=True)
    user_id = db.Column(db.Integer, db.ForeignKey("user.id"), nullable=False)
    file_data = db.Column(db.LargeBinary)
    filename = db.Column(db.String(300))

    def __init__(self, user_id, filename, data) -> None:
        self.file_data = data
        self.user_id = user_id
        self.filename = filename

src/__init__.py
from flask import Flask
from flask_sqlalchemy import SQLAlchemy
from os import path

db_name = "database.db"

app = Flask(__name__)
app.config['SECRET_KEY'] = "brrrrrrrrrrrrrr"
app.config["SQLALCHEMY_DATABASE_URI"] = f"sqlite:///{db_name}"

db = SQLAlchemy(app)

def start():
    global app, db

    from .views import routes, initialize_login
    from .models import User, Files

    with app.app_context():
        if not path.exists(db_name):
            db.create_all()

    initialize_login(app)

    app.register_blueprint(routes)

    return app

src/views.py
from flask import Blueprint, flash, render_template, redirect, url_for, request, send_file
from flask_login import LoginManager, login_user, current_user, logout_user, login_required
from werkzeug.security import generate_password_hash, check_password_hash

from .models import User, Files
from . import db

import io

routes = Blueprint("views", __name__)
login_manager = LoginManager()
login_manager.login_view = 'views.login'

def initialize_login(app):
    login_manager.init_app(app)

def get_filenames(current_user):
    return Files.query.filter_by(user_id=current_user.id).all()

@login_manager.user_loader
def load_user(id):
    return User.query.get(int(id))

@routes.route("/", methods=["GET", "POST"])
@login_required
def index():
    if request.method == "POST":
        file_id = request.form.get("file_id")
        file = Files.query.filter_by(id=file_id).first()
        if file:
            return send_file(
                io.BytesIO(file.file_data),
                mimetype='application/pdf'
            )

        return redirect(url_for("views.index"))
    
    return render_template("index.html", name=current_user.name, files=get_filenames(current_user))

@routes.route("/upload", methods=["POST"])
def upload():
    if 'file' not in request.files:
        flash('No file part')
        return redirect(request.url)

    file = request.files['file']

    if file.filename == '':
        flash('No selected file')
        return redirect(request.url)

    new_file = Files(user_id=current_user.id, filename=file.filename, data=file.read())
    db.session.add(new_file)
    db.session.commit()

    return redirect(url_for("views.index"))

@routes.route("/delete", methods=["POST"])
def delete():
    file_id = request.form.get("file_id")

    if file_id:
        file = db.session.get(Files, file_id)
        db.session.delete(file)
        db.session.commit()
        print(f"deleted file {request.form.get('file_id')}")

    return redirect(url_for("views.index"))

@routes.route("/login", methods=["GET", "POST"])
def login():
    if request.method == "POST":
        email = request.form.get("email")
        password = request.form.get("password")
        
        print(f"email = {email}, passwd = {password}")

        user = User.query.filter_by(email=email).first()
        if user:
            if check_password_hash(user.password, password):
                login_user(user, remember=True)
                flash("logged in")
                return redirect(url_for("views.index"), code=302)

            else:
                flash("incorrect password")
        else:
            flash("you need to signup first")
        
    return render_template("login.html")

@routes.route("/logout", methods=["GET", "POST"])
def logout():
    logout_user()
    return redirect(url_for("views.login"))

@routes.route("/signup", methods=["GET", "POST"])
def signup():
    if request.method == "POST":
        name = request.form.get("name")
        email = request.form.get("email")
        password1 = request.form.get("password1")
        password2 = request.form.get("password2")
        

        print(f"name = {name}, email = {email}, passwd = {password1}, {password2}")
        user = User.query.filter_by(email=email).first()
        if user:
            flash("email already in use")

        elif password1 != password2:
            flash("Re-Enter the same password")

        else:
            new_user = User(name=name, email=email, password=generate_password_hash(password1))
            db.session.add(new_user)
            db.session.commit()

            return redirect(url_for("views.login"))


    return render_template("signup.html")

src/templates/index.html
{% extends 'layout.html' %}

{% block content %}

<form action={{ url_for("views.upload") }} method="post" enctype="multipart/form-data">
	<label for="file">Upload file</label>
	<input type="file" name="file" required/>

	<button type="submit" >Upload</button>

</form>

<form action={{ url_for("views.index") }} method="post">
	<ol style="list-style: None;">
		{% for file in files %}
		<li>
			<input type="radio" value={{ file.id }} name="file_id" id={{ file.id }}/>
			<label for={{ file.id }}>{{ file.filename }}</label>
		</li>
		{% endfor %}

	</ol>

	<button type="submit" formaction={{ url_for("views.delete") }}>Delete file</button>
	<button type="submit" >Download file</button>
</form>

{% endblock %}

src/templates/layout.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8" />
  <title>Hello, world!</title>
  <meta name="viewport" content="width=device-width,initial-scale=1" />
  <meta name="description" content="" />
  <link rel="icon" href="favicon.png">
  <link rel="style" href={{ url_for("static", filename="style.css") }} />

</head>
<body>
	<div class="navbar">
		<a href={{ url_for("views.index") }}>dashboard</a>
		{% if name %}
		<a href={{ url_for("views.logout") }}>logout</a>
		{% else %}
		<a href={{ url_for("views.signup") }}>signup</a>
		<a href={{ url_for("views.login") }}>login</a>
		{% endif %}
	</div>

	{% with messages = get_flashed_messages(with_categories=true) %}
		{% if messages %}
		<ol>
			{% for category, message in messages %}
			<li class="{{ category }}" style="color: red;">{{ message }}</li>
			{% endfor %}
		</ol>
		{% endif %}
	{% endwith %}

	{% block content %}
	{% endblock %}

</body>
</html>

src/templates/login.html
{% extends 'layout.html' %}
{% block content %}

<form action={{ url_for("views.login") }} method="post">
	<label for="email">Enter Email</label>
	<input type="email" name="email" />

	<label for="password">Enter Password</label>
	<input type="password" name="password" />

	<button type="submit">Submit</button>

</form>

{% endblock %}

src/templates/signup.html
{% extends 'layout.html' %}

{% block content %}


<br />
<form action={{ url_for("views.signup") }} method="post" style="display: grid; margin: 20%;">

	<label for="name">Enter Name</label>
	<input type="text" name="name" style="margin-bottom: 2%;" required/>

	<label for="email">Enter Email</label>
	<input type="email" name="email" style="margin-bottom: 2%;" required/>

	<label for="password1">Enter Password</label>
	<input type="password" name="password1" style="margin-bottom: 2%;" required/>
	<label for="password2">Re-Enter Password</label>
	<input type="password" name="password2" style="margin-bottom: 2%;" required/>

	<button type="submit">Submit</button>

</form>
{% endblock %}